[server]
# If your file is named "Energy_Dashboard.py"
entrypoint = "1_Energy_Dashboard.py"

[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"

[browser]
gatherUsageStats = false 